apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginxingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ngsvc
            port:
              number: 80