apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-wp
  namespace: {{ .Values.namespace }}
  labels:
    app: nginx-wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-wp
  template:
    metadata:
      labels:
        app: nginx-wp
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodename }}
      containers:
        - name: wordpress-lemp
          image: {{ .Values.Container.Wordpress }}
          ports:
            - containerPort: 9000
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 10  
          resources:
            requests:
              memory: "300Mi"
              cpu: "200m"
            limits:
              memory: "600Mi"
              cpu: "400m"
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Values.WORDPRESS_DB_HOST }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.WORDPRESS_DB_USER }}
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: dbpassword
                  key: password
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.WORDPRESS_DB_NAME }}
          volumeMounts:
            - name: pvcmount
              mountPath: "/var/www/html"
        - name: nginx
          image: {{ .Values.Container.Nginx }}
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10 
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "300Mi"
              cpu: "250m"
          volumeMounts:
            - name: nginx-config
              mountPath: "/etc/nginx/conf.d/"
            - name: pvcmount
              mountPath: "/var/www/html"
      volumes:
        - name: nginx-config
          configMap:
            name: myconfigmap
        - name: pvcmount
          persistentVolumeClaim:
            claimName: myclaim  

            
            

