apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: premium-rwo
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi