apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlclaim
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: standard-rwo
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi